# Generated by Django 3.2 on 2023-07-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isfraud',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
